# Configuração da porta do servidor
server.port=8084


# Nome da aplicação
spring.application.name=api-consultas-softwave

# Desabilita configurações de banco de dados (caso existam dependências)
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none

# Configuracao do RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=secret
spring.rabbitmq.virtual-host=/

# Nome da exchange, fila e routing key
broker.exchange.name=processos.exchange
broker.queue.name=processos.queue
broker.routing.key=processos.key
